Change to new Initialization structure -> Factory + Bean Types
Implemented SetupFactory which creates Beans for the different SetupComponents.

SetupExecutor executes the Setup after Construction.

FIXME:
In setup for transaktionen
LazyInitializationException: failed to lazily initialize a collection of role: de.othr.sw.TRBank.entity.Kunde.konten, could not initialize proxy - no Session